---
- name: Retrieve Ansible Vault password from AWS Secrets Manager
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install boto3 if not already installed
      pip:
        name: boto3

    - name: Retrieve Ansible Vault password
      set_fact:
        vault_password: "{{ lookup('aws_secretsmanager', 'ansible_vault_password') }}"

    - name: Write Vault password to a temporary file
      copy:
        content: "{{ vault_password }}"
        dest: "/tmp/vault_pass.txt"
      run_once: true
